# Generated by Django 5.2.17 on 2026-10-02 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token_hash', models.CharField(db_index=True, max_length=64)),
                ('schema_version', models.CharField(default='trip-plan-v1', max_length=32)),
                ('rule_version', models.CharField(default='hos-property-carrying-70-8-v1', max_length=64)),
                ('input_json', models.JSONField()),
                ('route_json', models.JSONField()),
                ('timeline_json', models.JSONField()),
                ('logs_json', models.JSONField()),
                ('diagnostics_json', models.JSONField(default=dict)),
                ('validation_json', models.JSONField(default=dict)),
                ('provider_meta', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
